# Generated by Django 2.0.6 on 2018-07-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0007_auto_20180702_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='parent',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
