# Generated by Django 2.0.6 on 2018-07-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0009_ooraxcouruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cour',
            name='user',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutorat',
            name='user',
        ),
    ]
