# Generated by Django 2.0.6 on 2018-07-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0010_auto_20180703_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchatEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oorax.Evaluation')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oorax.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='AchatTutorat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oorax.Transaction')),
                ('tutorat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oorax.Tutorat')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oorax.Cour')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oorax.Transaction')),
            ],
        ),
        migrations.RemoveField(
            model_name='ooraxcouruser',
            name='cour',
        ),
        migrations.RemoveField(
            model_name='ooraxcouruser',
            name='customuser',
        ),
        migrations.DeleteModel(
            name='OoraxCourUser',
        ),
    ]
