# Generated by Django 2.0.6 on 2018-07-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0023_auto_20180711_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionquestion',
            name='juste',
        ),
    ]
