# Generated by Django 2.0.6 on 2018-07-17 17:10

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0028_auto_20180716_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionevaluation',
            name='reponse',
            field=django_mysql.models.ListCharField(models.IntegerField(default=None, null=True), max_length=66, size=6),
        ),
    ]
