# Generated by Django 2.0.6 on 2018-07-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0029_auto_20180717_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionevaluation',
            name='reponsse',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
