# Generated by Django 2.0.6 on 2018-07-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0031_remove_sessionevaluation_reponsse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionevaluation',
            old_name='date_transactions',
            new_name='date_evaluation',
        ),
    ]
