# Generated by Django 2.0.6 on 2018-07-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0034_question_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
    ]
