# Generated by Django 2.0.6 on 2018-08-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0035_customuser_email_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='ordre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
