# Generated by Django 2.0.6 on 2018-09-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0045_auto_20180910_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explication',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='visible',
            field=models.BooleanField(default=0),
        ),
    ]
