# Generated by Django 2.0.6 on 2018-11-07 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0050_cour_domaineid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_comment', models.CharField(blank=True, max_length=45, null=True)),
                ('contenu_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('cour_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='oorax.Cour')),
            ],
        ),
    ]
