# Generated by Django 2.0.6 on 2018-11-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0052_inscrit'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='prix_chapitre',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
