# Generated by Django 2.0.6 on 2018-11-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0054_inscription_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='cour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oorax.Chapitre'),
        ),
    ]
