# Generated by Django 2.0.6 on 2018-11-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0055_auto_20181121_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parrain',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bonus',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
