# Generated by Django 2.0.6 on 2018-11-28 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0057_chargementomoney'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServeurOrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('num_transfert', models.CharField(blank=True, max_length=200, null=True)),
                ('montant', models.FloatField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
