# Generated by Django 2.0.6 on 2018-12-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0058_serveurorange'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code_afiliation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
