# Generated by Django 2.0.6 on 2018-12-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0059_customuser_code_afiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code_afiliation',
            field=models.CharField(blank=True, default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='cour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oorax.Lesson'),
        ),
    ]
