# Generated by Django 2.0.6 on 2018-12-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0060_auto_20181203_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='ntfin',
            field=models.BooleanField(default=0),
        ),
    ]
