# Generated by Django 2.0.6 on 2018-12-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0061_check_ntfin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fonction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
