# Generated by Django 2.0.6 on 2019-01-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0062_customuser_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='NULL', upload_to='logo'),
            preserve_default=False,
        ),
    ]
