# Generated by Django 2.0.6 on 2019-02-04 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0063_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrit',
            name='date_inscription',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
