# Generated by Django 2.0.6 on 2018-09-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cnt', models.CharField(blank=True, max_length=45, null=True)),
                ('description_cnt', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_mat', models.CharField(blank=True, max_length=45, null=True)),
                ('description_mat', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_pro', models.CharField(blank=True, max_length=45, null=True)),
                ('description_pro', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_sess', models.CharField(blank=True, max_length=45, null=True)),
                ('description_sess', models.CharField(blank=True, max_length=200, null=True)),
                ('prix_sess', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniteEnseign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_ue', models.CharField(blank=True, max_length=45, null=True)),
                ('description_ue', models.CharField(blank=True, max_length=200, null=True)),
                ('matiere_ue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservation.Matiere')),
            ],
        ),
        migrations.CreateModel(
            name='UserEleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(blank=True, max_length=45, null=True)),
                ('description_user', models.CharField(blank=True, max_length=200, null=True)),
                ('session_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservation.Session')),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='unite_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservation.UniteEnseign'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='session_mat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservation.Session'),
        ),
        migrations.AddField(
            model_name='centre',
            name='session_cnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservation.Session'),
        ),
    ]
