# Generated by Django 2.0.6 on 2018-09-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='prix',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
