# Generated by Django 2.0.6 on 2018-07-03 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0008_auto_20180703_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='OoraxCourUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oorax.Cour')),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
