# Generated by Django 2.0.6 on 2018-07-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0011_auto_20180703_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
