# Generated by Django 2.0.6 on 2018-07-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0013_auto_20180703_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='libelle',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
