# Generated by Django 2.0.6 on 2018-07-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0017_option_optionquestion_sessionevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='parent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
