# Generated by Django 2.0.6 on 2018-07-09 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0018_auto_20180709_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_transaction',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
