# Generated by Django 2.0.6 on 2018-07-09 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0020_remove_transaction_date_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_transactions',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
