# Generated by Django 2.0.6 on 2018-07-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0021_transaction_date_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionquestion',
            name='juste',
            field=models.BooleanField(default=True),
        ),
    ]
