# Generated by Django 2.0.6 on 2018-07-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0022_auto_20180711_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionquestion',
            name='juste',
            field=models.BooleanField(default=0),
        ),
    ]
