# Generated by Django 2.0.6 on 2018-07-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0024_remove_optionquestion_juste'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionquestion',
            name='juste',
            field=models.BooleanField(default=0),
        ),
    ]
