# Generated by Django 2.0.6 on 2018-07-13 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0025_optionquestion_juste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionevaluation',
            old_name='point',
            new_name='reponse',
        ),
        migrations.AddField(
            model_name='sessionevaluation',
            name='date_transactions',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
