# Generated by Django 2.0.6 on 2018-07-16 13:02

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0027_evaluation_typeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='typeId',
            field=django_mysql.models.ListCharField(models.IntegerField(default=None, null=True), max_length=66, size=6),
        ),
    ]
