# Generated by Django 2.0.6 on 2018-07-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0030_sessionevaluation_reponsse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionevaluation',
            name='reponsse',
        ),
    ]
