# Generated by Django 2.0.6 on 2018-07-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0032_auto_20180717_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionevaluation',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
