# Generated by Django 2.0.6 on 2018-08-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0036_chapitre_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cour',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cour',
            name='image',
            field=models.FileField(default='Null', upload_to='logo'),
            preserve_default=False,
        ),
    ]
