# Generated by Django 2.0.6 on 2018-08-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0037_auto_20180808_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cour',
            name='image',
            field=models.ImageField(upload_to='logo'),
        ),
    ]
