# Generated by Django 2.0.6 on 2018-09-04 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0042_auto_20180904_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapevaluation',
            name='evaluation_id',
        ),
        migrations.AddField(
            model_name='chapevaluation',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
