# Generated by Django 2.0.6 on 2018-09-10 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0043_auto_20180904_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionevaluation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionevaluation',
            name='evaluation',
            field=django_mysql.models.ListCharField(models.IntegerField(default=None, null=True), max_length=66, size=6),
        ),
    ]
