# Generated by Django 2.0.6 on 2018-09-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0044_auto_20180910_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='objectif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cour',
            name='objectif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='objectif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
