# Generated by Django 2.0.6 on 2018-09-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0046_auto_20180912_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=0)),
            ],
        ),
    ]
