# Generated by Django 2.0.6 on 2018-09-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oorax', '0047_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='temps',
            field=models.BooleanField(default=0),
        ),
    ]
