# Generated by Django 2.0.6 on 2018-09-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_session_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='prix',
        ),
        migrations.AddField(
            model_name='usereleve',
            name='prix_user',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
