# Generated by Django 2.0.6 on 2018-09-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20180925_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usereleve',
            old_name='prix_user',
            new_name='solde',
        ),
    ]
